#ifndef __SARADC_CTRL_IRQ_H__
#define __SARADC_CTRL_IRQ_H__

#define SARADC_CTRL_NUM_IRQS 16

typedef enum
{
  SARADC_CTRL_IRQ_DMA_READ_ERR = 0,
  SARADC_CTRL_IRQ_DMA_WRITE_ERR = 1,
  SARADC_CTRL_IRQ_SUM_WRITTEN_EVT = 2,
  SARADC_CTRL_IRQ_LIST_DONE_EVT = 3,
  SARADC_CTRL_IRQ_SADR_DONE_NEMPTY = 4,
  SARADC_CTRL_IRQ_SADR_NEW_NFULL = 5,
  SARADC_CTRL_IRQ_OOR0 = 6,
  SARADC_CTRL_IRQ_OOR1 = 7,
  SARADC_CTRL_IRQ_OOR2 = 8,
  SARADC_CTRL_IRQ_OOR3 = 9,
  SARADC_CTRL_IRQ_OOR4 = 10,
  SARADC_CTRL_IRQ_OOR5 = 11,
  SARADC_CTRL_IRQ_OOR6 = 12,
  SARADC_CTRL_IRQ_OOR7 = 13,
  SARADC_CTRL_IRQ_OOR8 = 14,
  SARADC_CTRL_IRQ_OOR9 = 15
} saradc_ctrl_irq_t;

#endif
