#ifndef __SPI_IRQ_H__
#define __SPI_IRQ_H__

#define SPI_NUM_IRQS 16

typedef enum
{
  SPI_IRQ_EVT_RX_FIFO_OV_ERR = 0,
  SPI_IRQ_EVT_RX_FIFO_UR_ERR = 1,
  SPI_IRQ_EVT_TX_FIFO_OV_ERR = 2,
  SPI_IRQ_EVT_TX_FIFO_UR_ERR = 3,
  SPI_IRQ_EVT_SOT = 4,
  SPI_IRQ_EVT_EOT = 5,
  SPI_IRQ_EVT_SDI = 6,
  SPI_IRQ_EVT_SCLK_TIMEOUT = 7,
  SPI_IRQ_EVT_SHIFT_DONE = 8,
  SPI_IRQ_RX_FIFO_NEMPTY = 9,
  SPI_IRQ_RX_FIFO_TIMEOUT = 10,
  SPI_IRQ_RX_FIFO_HIGH_WATER = 11,
  SPI_IRQ_RX_FIFO_FULL = 12,
  SPI_IRQ_TX_FIFO_EMPTY = 13,
  SPI_IRQ_TX_FIFO_LOW_WATER = 14,
  SPI_IRQ_TX_FIFO_NFULL = 15
} spi_irq_t;

#endif
